### ISSUE TITLE
I have to uninstall and reinstall every time I shut down my computer

### ISSUE THREAD

**Issue by allyweller** [danabr/SupportNotifications#11]
Every time I shut down my computer I have to reinstall your plugin. It won't configure or take my pword. So then I'll reinstall and it will make me reconfigure every time. It's frustrating. I love the plugin but hate having to reinstall it all the time. 

Thanks,

**Comment by danabr** [comment]
Hi,

I've never heard of this problem before. Which version of the plugin are you using (see Tools->Extensions)? Which browser and which browser version? Has the plugin always behaved like this?

Instead of re-installing, have you tried to use the "Reset"-link at the login page? You should not need to use this functionality (or re-install, for that matter) at all.

**Comment by allyweller** [comment]
Here's the version I'm using.
https://chrome.google.com/webstore/detail/support-notifications/enfpphpelchogekkdfjicghaigahdldc

I'm using Chrome version 31.0.1650.63.

It has always behaved like this. Since I installed it last week or the week
before.

Suddenly today when I logged on it worked. It gave me the option to enter
my pword. Before today, ever time I would click the icon it would say
"check for new tickets" and "configure new settings" but I wasn't logged
in.

Thanks,

_Ally Weller_
Community Manager
307.855.4011 ex. 116 | twitter https://twitter.com/AllysonWeller |
lhttp://www.linkedin.com/profile/edit?trk=tab_pro
linkedin http://www.linkedin.com/profile/edit?trk=tab_prohttps://mail.google.com/

PitchEngine > get the word out™
http://pitchengine.com | twitter http://twitter.com/pitchengine |
facebookhttp://facebook.com/pitchengine
 | pinterest http://pinterest.com/pitchengine/

**Comment by danabr** [comment]
Are you using the Zendesk, Freshdesk or getsatisfaction integration?

I've noticed that for Freshdesk you now need to login on their site, before
the extension is able to retrieve tickets. It wasn't like this before, but
I think it is something that has changed on Freshdesk's side.

//Daniel

**Comment by allyweller** [comment]
It seems to be working now. (You must have fixed it.) :)

I'll let you know if there are any other issues. Thanks for the plugin!

_Ally Weller_
Community Manager
307.855.4011 ex. 116 | twitter https://twitter.com/AllysonWeller |
lhttp://www.linkedin.com/profile/edit?trk=tab_pro
linkedin http://www.linkedin.com/profile/edit?trk=tab_prohttps://mail.google.com/

PitchEngine > get the word out™
http://pitchengine.com | twitter http://twitter.com/pitchengine |
facebookhttp://facebook.com/pitchengine
 | pinterest http://pinterest.com/pitchengine/
