### ISSUE TITLE
Freshdesk API

### ISSUE THREAD

**Issue by reevery** [danabr/SupportNotifications#12]
Our freshdesk account authenticates using Google accounts. As a result, I don't have a password. Could you enable support for authentication to be done using API key instead?

**Comment by danabr** [comment]
Hi,

I'll mark this as a feature request. Note that there is no active development from my side, though, since I do not use the extension anymore and would like to prioritize other things.

I'll happily merge a pull-request, though.

**Comment by tekNorah** [comment]
@reevery @danabr - I use google authentication, as well.  As a workaround, you can set a password for your account on Freshdesk by having the website send you a forgot password email.  Follow these steps to enable a regular password on your account: 
1. Click your profile icon in the upper right corner
2. Click _Sign Out_
3. Click _Login_
4. Click _forgot your password?_
5. Enter your email address associated with your Google account
6. Click _Reset my password_
7. Access your email and click the link for _Click here to reset the password_
8. Enter a password and confirm password
9. Enter this password into the config for this extension

**Comment by danabr** [comment]
Hi. This extension has been officially abandoned.
