### ISSUE TITLE
Feature Request: Freshservice Integration

### ISSUE THREAD

**Issue by RSJ900509** [danabr/SupportNotifications#13]
Hi Danabr

I see that your app works for FreshDesk but not FreshService.

FreshService is made by FreshDesk so perhaps you could find some way to integrate it.

I currently experience frustration with FreshService as I cannot know when a new ticket has arrived until I physically go to the Dashboard or Tickets page and it reloads.

A sound notification would make this a whole heap easier as I am busy in the office and cannot reload the Dashboard all day to look for new tickets.

If you can investigate this I would be eternally grateful.

Kind Regards,
Rowan

**Comment by danabr** [comment]
Hi Rowan,

As noted in the README, this project is no longer actively maintained. I don't use the software myself and don't have any accounts to test with. More recently, it seems like most service desk companies have released their own apps and extensions to help with these kinds of issues. Perhaps there is something for FreshService already?

Sorry to make you disappointed.

Regards,
Daniel

**Comment by danabr** [comment]
Hi. This extension has been officially abandoned.
