### ISSUE TITLE
Getting Error: NETWORK_ERR: XMLHttpRequest Exception 101

### ISSUE THREAD

**Issue by sdelmas** [danabr/SupportNotifications#3]
Sorry if I am doing something stupid here.

It seems that the request to .../views.json works fine, while the request to ../rules/<id>.json fails with the above error. So I am pretty sure my credentials are right, and the rule seems to also be right. When I hit the rules url in my browser it takes a few seconds to return, but it then does return with real data.

I changed my view (I did check that it's using the right view) to be empty, just in case it's the data in the query. The request returns much faster, but still produces the above error message.

So does this work for anyone else at this point? Is this something broken at Zendesk? Anything else I can do?

**Comment by danabr** [comment]
Hi,

Can you describe what you do when you get this error? Is it on the configuration page, when you choose "Test authentication details", or is it when you click "Check for new tickets"?

Can you try this out:
1. Click the Chrome wrench, then "Tools", then "Extensions"
2. Check the "Developer mode" checkbox(I'm not sure about the english name)
3. Click the arrow to the left of the SupportNotifications icon.
4. Click on bg.html. A new window should pop up.
5. Click console in the new window.
6. Type "SupportNotifications.providers.Zendesk.ruleId", and press Enter

This is the id of the exact rule/view used by SupportNotifications. You can test the response from Zendesk by visiting the url http://mycompanid.zendesk.com/rules/XXXXXXX.xml, where XXXXXXX is the rule id you got. You should get a list of tickets in XML format. If not, please tell me what you get instead.

In addition, the console should contain details regarding any error that occured while SupportNotifications tried to download ticket data. It may provide a more detailed error than what you have got so far.

**Comment by sdelmas** [comment]
Thanks for the quick response... I appreciate you taking the time to help (and to implement it in the first place :-).

I should have been more clear... what I see in the interface is that my tickets never get retrieved. The ruleId is my correct rule number. Doing the rules request directly results in a nicely formatted XML (I am attaching a slightly cleaned up/anonymized version). I also get fine results with .json instead of .xml.  The console shows the exception for the rules request.

I set a breakpoint, and as expected the xhr.send() is who throws the exception. The only thing I can come up with is that the resulting XML/content is malformed. However, as I said before... I changed my view, and even an empty view throws this error for me.

I won't have access to mail for the next few days, so I will have to get back to you Monday of there is more. I am happy to do whatever you need to debug this further... 

Thanks,
Sven

**Comment by danabr** [comment]
I'll try to look into it during the next few days. As far as google tells me, it seems to be a permission error, i.e. the extension is trying to access a page it is not allowed to access. But I will have to dig deeper into it when I find the time.

**Comment by sdelmas** [comment]
Yeah... I saw that too... it's strange that it would happen to just me though. So maybe it's a browser setup issue (I am on a OS X Lion). I looked, and couldn't find anything suspicious (my browser's security is pretty open, and set to ask if it's uncertain). It's also interesting that it's only the rules call that fails... maybe those are served by Zendesk from a different server (just thinking out loud :-)? I found one article that was talking about getting this when the response if malformed, but that's why I tried the empty view.... that should be pretty much clean.

If there is anything I can do to help, please let me know.

Thanks,
Sven

**Comment by danabr** [comment]
Sven, can you send me an email with the anonymified response you talked about previously? Attachments are apperantly ignored by github. You can find my email address on my profile page.

**Comment by sdelmas** [comment]
Thanks for looking at this... let me know if there is anything else I can do...

**Comment by danabr** [comment]
Closing due to age, and no new reports of the issue.
