### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by Comprensivo** [danabr/SupportNotifications#4]
Hi

I cannot connect to zendesk - Udpate attempt fails. Has something changed with Zendesk so it won't update anymore or is it something else?

I have tried with 2 different zendesk accounts and on 2 different network locations. Same result.

**Comment by Comprensivo** [comment]
Any news on this?

**Comment by danabr** [comment]
Sorry, I tried to answer from my phone, but it seems like my answer was not delivered. Have you tried the now offical zendesk extensions, provided by zendesk themselfes? SupportNotifications was only intended as a temporary solution until they got released, so I'm not putting much effort into this anymore. Perhaps I can have a look at it this weekend.

//Daniel

**Comment by Comprensivo** [comment]
Hi Daniel. 

You're app shows new unassigned tickets, where the official app only shows what's going on in my stream in zendesk... Yours is better :-) 

Please fix :-P

## Br Carsten 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

Daniel Abrahamsson reply@reply.github.com skrev:

Sorry, I tried to answer from my phone, but it seems like my answer was not delivered. Have you tried the now offical zendesk extensions, provided by zendesk themselfes? SupportNotifications was only intended as a temporary solution until they got released, so I'm not putting much effort into this anymore. Perhaps I can have a look at it this weekend.

//Daniel

---

**Comment by danabr** [comment]
My testaccount still works perfectly. 

Which version of chrome/chromium are you using. I am using chromium 17.

What do you get if you reenter your credentials, then press the test button?

What does entering "http://YOURCOMPANYID.zendesk.com/views.json" give you? (perhaps it requires https?)

//Daniel

**Comment by Comprensivo** [comment]
Hi Daniel

Im running Chrome 17.0.963.56 m.

When I try to reenter info it just says in a yellow bar in the top: The service seems to be unavailable at the moment.

The views.json gives me:
{"count":10,"views":[{"position":0,"title":"My unsolved tickets","output":{"columns":[{"name":"score"},{"name":"description"},{"name":"requester"},{"name":"created"},{"name":"type"},{"name":"priority"}],"type":"table","group":"status","order_asc":false,"order":"score"},"id":25750876,"owner_id":137098,"is_active":true,"per_page":15,"owner_type":"Account"},{"position":1,"title":"Unassigned tickets","output":{"columns":[{"name":"score"},{"name":"description"},{"name":"requester"},{"name":"created"},{"name":"priority"},{"name":"group"}],"type":"table","group":null,"order_asc":false,"order":"created"},"id":25750901,"owner_id":137098,"is_active":true,"per_page":15,"owner_type":"Account"},{"position":2,"title":"All unsolved tickets","output":{"columns":[{"name":"score"},{"name":"description"},{"name":"requester"},{"name":"created"},{"name":"priority"},{"name":"updated"},{"name":"organization"}],"type":"table","group":"assignee","order_asc":false,"order":"score"},"id":25750896,"owner_id":137098,"is_active":true,"per_page":15,"owner_type":"Account"},{"position":3,"title":"Recently updated tickets","output":{"columns":[{"name":"description"},{"name":"requester"},{"name":"created"},{"name":"priority"},{"name":"group"},{"name":"assignee"}],"type":"table","group":"status","order_asc":false,"order":"updated"},"id":25750906,"owner_id":137098,"is_active":true,"per_page":15,"owner_type":"Account"},{"position":9999,"title":"New tickets in your groups","output":{"columns":[{"name":"score"},{"name":"description"},{"name":"requester"},{"name":"created"},{"name":"priority"},{"name":"assignee"}],"type":"table","group":"group","order_asc":false,"order":"created"},"id":25750886,"owner_id":137098,"is_active":true,"per_page":15,"owner_type":"Account"},{"position":9999,"title":"Pending tickets","output":{"columns":[{"name":"description"},{"name":"requester"},{"name":"created"},{"name":"priority"},{"name":"group"},{"name":"assignee"}],"type":"table","group":"updated","order_asc":false,"order":"score"},"id":25750911,"owner_id":137098,"is_active":true,"per_page":15,"owner_type":"Account"},{"position":9999,"title":"Recently solved tickets","output":{"columns":[{"name":"description"},{"name":"requester"},{"name":"created"},{"name":"solved"},{"name":"priority"},{"name":"group"}],"type":"table","group":"assignee","order_asc":false,"order":"solved"},"id":25750891,"owner_id":137098,"is_active":true,"per_page":15,"owner_type":"Account"},{"position":9999,"title":"SupportNotifications","output":{"columns":[{"name":"satisfaction_score"},{"name":"description"},{"name":"requester"},{"name":"created"},{"name":"status"},{"name":"assignee"}],"type":"list","group":null,"order_asc":false,"order":"created"},"id":25989522,"owner_id":137098,"is_active":true,"per_page":15,"owner_type":"Account"},{"position":9999,"title":"Unsolved tickets in your groups","output":{"columns":[{"name":"score"},{"name":"description"},{"name":"requester"},{"name":"created"},{"name":"status"}],"type":"table","group":"group","order_asc":false,"order":"score"},"id":25750881,"owner_id":137098,"is_active":true,"per_page":15,"owner_type":"Account"},{"position":10000,"title":"Rated tickets from the last 7 days","output":{"columns":[{"name":"status"},{"name":"description"},{"name":"requester"},{"name":"created"},{"name":"assignee"},{"name":"satisfaction_score"}],"type":"table","group":"satisfaction_score","order_asc":true,"order":"updated"},"id":25976011,"owner_id":137098,"is_active":true,"per_page":15,"owner_type":"Account"}],"show_empty_views":true}

Thx.

-----Oprindelig meddelelse-----
Fra: Daniel Abrahamsson [mailto:reply@reply.github.com] 
Sendt: 3. marts 2012 08:58
Til: Comprensivo
Emne: Re: [SupportNotifications] Cannot update (#4)

My testaccount still works perfectly. 

Which version of chrome/chromium are you using. I am using chromium 17.

What do you get if you reenter your credentials, then press the test button?

What does entering "http://YOURCOMPANYID.zendesk.com/views.json" give you? (perhaps it requires https?)

//Daniel

---

Reply to this email directly or view it on GitHub:
https://github.com/danabr/SupportNotifications/issues/4#issuecomment-4299177

## 

I am using the free version of SPAMfighter for private users.
It has removed 2696 spam emails to date.
Paying users do not have this message in their emails.
Try www.SPAMfighter.com for free now!

**Comment by Comprensivo** [comment]
Views.json also changes the url to: zendesk.com/api/v1/views.json

-----Oprindelig meddelelse-----
Fra: Daniel Abrahamsson [mailto:reply@reply.github.com] 
Sendt: 3. marts 2012 08:58
Til: Comprensivo
Emne: Re: [SupportNotifications] Cannot update (#4)

My testaccount still works perfectly. 

Which version of chrome/chromium are you using. I am using chromium 17.

What do you get if you reenter your credentials, then press the test button?

What does entering "http://YOURCOMPANYID.zendesk.com/views.json" give you? (perhaps it requires https?)

//Daniel

---

Reply to this email directly or view it on GitHub:
https://github.com/danabr/SupportNotifications/issues/4#issuecomment-4299177

## 

I am using the free version of SPAMfighter for private users.
It has removed 2696 spam emails to date.
Paying users do not have this message in their emails.
Try www.SPAMfighter.com for free now!

**Comment by danabr** [comment]
That's interesting. Do you use plain http or https?

**Comment by danabr** [comment]
Also, can you check what the console log says?

Open the Extensions page (Wrench => Tools => Extensions), check the "developer mode" checkbox, click on he arrow left to SupportNotifications, then on bg.html. Open the "Console" tab.

Keeping the Console open, click on the "Test" button below your zendesk credentials. Does it print anything in the console?

**Comment by danabr** [comment]
Closing due to missing info.
