### ISSUE TITLE
Feature request: Choose Freshdesk default view/notifications.

### ISSUE THREAD

**Issue by astedfast** [danabr/SupportNotifications#6]
I have created a default view for Freshdesk, so that I can see a particular set of tickets.  It would be great if your extension could check for only those types of tickets, or allow the option for importing the different views in an account, in case we do want to see all tickets sometimes, etc.  Naturally, I'd love the notification link to send me to my custom default view.  Thank you!

**Comment by danabr** [comment]
Hi,

I've just relased version 1.1.1 which allows you to specify which filter or view id to use. Just enter the filter name or the view id in the "Filter name" field and everything should just work.

You find the view id as the very last part of the URL when you open the view,  e.g. http://mycompany.freshdesk.com/helpdesk/tickets/view/<b>135296</b>

Regards,
Daniel Abrahamsson
