### ISSUE TITLE
cant find my freshdesk details

### ISSUE THREAD

**Issue by Showcase-Joz** [danabr/SupportNotifications#8]
there is no evidence of a company id on freshdesk, so where do i find it? hoping i get that working, hows the filter work?

**Comment by danabr** [comment]
The "company id" is the first part in your freshdesk subdomain: e.g. for "example.freshdesk.com", the company id would be "example".

When it comes to filters, see Issue 6 (https://github.com/danabr/SupportNotifications/issues/6).

Regards,
Daniel Abrahamsson
