### ISSUE TITLE
Seems to stop working once https is enabled in Freshdesk

### ISSUE THREAD

**Issue by RCheesley** [danabr/SupportNotifications#9]
Hi folks,

Loved the extension but since we enabled https (I think this is what caused it) I now no longer get notifications, even if I manually query using the link it doesn't show any tickets.

We need https mode because our Freshdesk Facebook app requires it to be enabled.

Hoping it's an easy to fix bug!

Ruth

**Comment by danabr** [comment]
Hi,

The extension explicitly uses http. We would need to add a checkbox to use https. It should not be a big change, but I don't think I will be able to test it. I can see if I find time to make the change during some lunch break and then let you try it out.

I do not use the extension myself anymore, so it is getting hard to make sure it keeps working. I'll see if I can find someone who can take over maintenance.

**Comment by RCheesley** [comment]
Thanks, unfortunately to use the apps associated with Freshdesk, https connections are a must - I guessed that was what the problem is!

Ruth

**Comment by danabr** [comment]
Hi, I just published a new version, 1.2.0, that allows you to choose to use https for Zendesk and Freshdesk.

The update should be available in Chrome Web Store soon, but you can also find it here if you want to install it manually (using the developer tools in chrome): https://github.com/danabr/SupportNotifications/releases

Please reopen this issue if the problem still persists.

**Comment by RCheesley** [comment]
Awesome, thanks - will check it when it becomes available!
